import "./system.css";

import type { Metadata } from "next";

import { QueryProvider } from "@/configs/providers/query";
import { ThemeProvider } from "@/configs/providers/theme";
import { ThirdwebProvider } from "@/configs/providers/thirdweb";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={"antialiased"}>
				<ThemeProvider>
					<QueryProvider>
						<ThirdwebProvider>{children}</ThirdwebProvider>
					</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
